name: build-ios-app
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
       MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
       APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
       APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
       APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Echo environment variables
        run: |
          # Use conditional checks to ensure secrets are set, without directly echoing them
          echo "$MATCH_PASSWORD"
          echo "$APP_STORE_CONNECT_API_KEY_KEY_ID"
          echo "$APP_STORE_CONNECT_API_KEY_ISSUER_ID"
          echo "$APP_STORE_CONNECT_API_KEY_KEY"
          
      - name: Change to build-ios-app directory and run Fastlane
        working-directory: Source
        run: |
          fastlane uploadToAppStore
