name: build-ios-app
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
       MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
       APP_STORE_CONNECT_API_KEY_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}'
       APP_STORE_CONNECT_API_KEY_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}'
       APP_STORE_CONNECT_API_KEY_KEY: '${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}'
    steps:
      - uses: actions/checkout@v4
      - name: Echo environment variables
        run: |
          # Use conditional checks to ensure secrets are set, without directly echoing them
          if [ -z "$env:SUPER_SECRET" ]; then echo "MATCH_PASSWORD is not set"; else echo "MATCH_PASSWORD is set"; fi
          if [ -z "${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}" ]; then echo "APP_STORE_CONNECT_API_KEY_KEY_ID is not set"; else echo "APP_STORE_CONNECT_API_KEY_KEY_ID is set"; fi
          if [ -z "${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}" ]; then echo "APP_STORE_CONNECT_API_KEY_ISSUER_ID is not set"; else echo "APP_STORE_CONNECT_API_KEY_ISSUER_ID is set"; fi
          if [ -z "${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}" ]; then echo "APP_STORE_CONNECT_API_KEY_KEY is not set"; else echo "APP_STORE_CONNECT_API_KEY_KEY is set"; fi

      - name: Change to build-ios-app directory and run Fastlane
        working-directory: Source
        run: |
          fastlane beta --verbose
          # It's not safe to directly echo secrets, so this line is commented out
          # echo "${{ secrets.P8_AUTH_KEY }}" > secretKey.p8
