name: build-ios-app
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env: # Ensure this is properly aligned within the 'build' job
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Change to build-ios-app directory and run Fastlane
        working-directory: Source
        run: fastlane beta --verbose
